language: go

go:
  - 1.13.x
  - 1.14.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - SHELLCHECK_VERSION=0.7.1 HADOLINT_VERSION=1.17.6

before_install:
  - wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64
  - tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest
  - chmod +x hadolint
  - ./shellcheck-latest/shellcheck --version
  - ./hadolint --version
  - make deps

script:
  - make all
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck bop-docker'
  - ./hadolint Dockerfile
