name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 12 */15 * *'

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    env:
      SRC_DIR: src/github.com/${{ github.repository }}
      GO111MODULE: auto

    strategy:
      matrix:
        go: [ '1.15.x', '1.16.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Setup PATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "GOBIN=${{ github.workspace }}/bin" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Build binary
        working-directory: ${{env.SRC_DIR}}
        run: make all

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Go

    env:
      SHELLCHECK_VERSION: 0.7.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Shellcheck
        run: |
          wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
          tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
          mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest

      - name: Print Shellcheck version info
        run: ./shellcheck-latest/shellcheck --version

      - name: Check scripts
        run: bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck bop-docker'

  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    needs: Go

    env:
      HADOLINT_VERSION: 2.3.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64
          chmod +x hadolint
      
      - name: Print Hadolint version info
        run: ./hadolint --version

      - name: Check Docker files
        run: ./hadolint Dockerfile
